### ISSUE TITLE
Can't open 'null'

### ISSUE THREAD

**Issue by alexisabril** [jasmine-contrib/grunt-jasmine-runner#11]
Running "jasmine" task
Testing jasmine specs via phantom

Running PhantomJS...ERROR
>> Can't open 'null'

I'm curious if anyone has had this issue when using the runner through loadNpmTasks. Cloning the project and running the gruntfile contained within grunt-jasmine-runner works fine, however when loading this module as an npm task, this error occurs.

Specifics for error:
- only affects versions >= 0.5.6
- jasmine-server works fine

Error starts on line 131 of tasks/lib/phantomjs.js:

```
grunt.task.getFile('lib/phantomjs/bootstrap.js'),
```

Grunt internally uses `grunt.task.searchDirs` for the above command, however this array is empty. This only occurs when loading via npm at the moment. It seems `searchDirs` is populated during the `loadTasks` method.

**Comment by jsoverson** [comment]
What version of grunt are you using? I recently broke future compatibility with grunt 0.4.0 and need to make some changes. I've seen this using grunt on the devel branch and devel npm module, but not with 0.3.*

**Comment by alexisabril** [comment]
Currently using 0.3.15.

I'm not 100% sure why the task is losing context, but by the time phantomRunner(), runPhantom() and ultimately, phantomjs.spawn() are called, grunt.task.searchDirs has lost context(and subsequently an empty array).

**Comment by jsoverson** [comment]
I'll revert some changes that I think broke this and this should address 0.4.0 issues at the same time.

Thanks for bringing this up, @alexisabril

**Comment by jsoverson** [comment]
I reverted some changes and confirm they work for me on 0.3.16 and 0.4.0. Can you install directly from this repo and confirm that it fixes this issue?

**Comment by alexisabril** [comment]
Confirmed. Just pulled latest and everything looks to be running once again.

**Comment by jsoverson** [comment]
Thanks for the confirmation, published 0.5.9 to npm.
