### ISSUE TITLE
Unable to run 'grunt jasmine' and 'grunt jasmine-server' side by side

### ISSUE THREAD

**Issue by pavanpodila** [jasmine-contrib/grunt-jasmine-runner#12]
Hello,
        I have a `grunt watch` task that looks at changes to js/spec files and restarts the `jasmine` task. However I also have the `grunt jasmine-server` running alongside. I am doing that to debug some of my tests in the browser. 

When the js/spec files change, `grunt watch` simply crashes since the `jasmine` task seems to start listening on the same port as the `jasmine-server`, causing an exception. 

Is there any way I can keep the `jasmine-server` running and have grunt watch auto-generate the specrunner.html without crashing ?

Thanks

**Comment by pavanpodila** [comment]
Nevermind...it was a config issue at my end

**Comment by jsoverson** [comment]
Thanks for the follow up @pavanpodila

**Comment by pavanpodila** [comment]
As a separate note, is there a way to autogenerate the _SpecRunner.html file when you have a jasmine-server running. I see that adding a new file to my /test folder does not regenerate the _SpecRunner.

Cheers!

**Comment by jsoverson** [comment]
There isn't, but extracting a parts of these tasks to be runnable in different ways is on the roadmap.

**Comment by pavanpodila** [comment]
Cool.. Look forward to that. I was thinking of making a custom task for the time being.
