### ISSUE TITLE
Specs not running, no error messages.

### ISSUE THREAD

**Issue by RodEsp** [jasmine-contrib/grunt-jasmine-runner#14]
Hi, I'm having a bit of a problem trying to get my specs to run from a different folder than the one containing my _SpecRunner.

My grunt.js configuration looks like this:

```
    jasmine: {
            src: ['../..app/js/main.js'],
            specs: ['../../test/tests1.js', '../../test/other/tests2.js'],
            helpers: ["../../app/lib/jquery.js", "../../app/lib/require.js", "../../test/requireConfig.js"],
            amd: true
}
```

This is what the require comes out to on my _SpecRunner.html:

```
    require([        
            'C:/foo/bar/test/tests1.js' ,       
            'C:/foo/bar/test/other/tests2.js'       
     ]);
```

tests1.js is a very simple file:

```
    define(["../../app/js/main.js"], function (main) {
    describe("Main", function () {
        it("Should expect correct logic.", function () {
            expect(true).toBeTruthy();
        });
    });
});
```

tests2.js is more complicated but I get the same type of response if I only include/use tests1.js
This is what I'm getting in the console:

```
C:\foo\bar\build\grunt>grunt.cmd jasmine
Running "jasmine" task
Testing jasmine specs via phantom
0 specs, 0 failures in 0.001s.

Done, without errors.
```

This is my folder structure:

```
foo/
-->bar/
------->app/
----------->js/
-------------->main.js
------->build/
----------->grunt/
-------------->grunt.js
-------------->_SpecRunnet.html
-------------->node_modules/ -> grunt-jasmine-runner
-------->test/
----------->tests1.js
----------->other/
-------------->tests2.js
```

Worst case scenario I should be getting  at least 1 passed test, shouldn't I?

**Comment by jsoverson** [comment]
Have you looked into what the _SpecRunner.html file includes?

I don't know what the results will be when trying to run grunt outside of the root of your relevant source but it won't work (obviously).

The logic to normalize paths is pretty dumb. It can be made more intelligent but I don't know if it's really worth it to spend the time since standard grunt usage has it at the root of an app directory.

**Comment by joshuacc** [comment]
I'm also running into this problem with the following directory structure.

```
myproject/
    dist/
    node_modules/
    spec/
    src/
    grunt.js
```

Do you have any suggestions?

**Comment by joshuacc** [comment]
Looking into things a little more, I think the issue may be that the _SpecRunner file is starting all JS paths with a `/`.

**Comment by RodEsp** [comment]
Heya joshuacc, I thought so at first too but that's not it. I made a simple change to fix that and I still get the same behavior.
Inside your grunt-jasmine-runner folder go to tasks -> lib -> jasmine.js
Find the `getRelativeFileList` function at the bottom and change the `files =` right side to the following: 

> files = grunt.util._(files).map(function(file){
>     var finalPath = path.resolve(file).replace(base,'').replace(/\/g,'/');
>     return finalPath.charAt(0) === "/" ? finalPath.substring(1) : finalPath;
>   });

On that same note all my _SpecRunner.html includes are correct and it is finding all the files.
If I run jasmine-server then I do get test cases but I'd very much like to use PhantomJS to test and not my browser.

**Comment by joshuacc** [comment]
@RodEsp Yeah. I see what you mean. Still broken here as well.

I'm quite happy to consider changing my project's folder structure, but I'm not sure how I should change it to play nicely with grunt-jasmine-runner.

**Comment by jsoverson** [comment]
What version of jasmine-runner are you using? There was an issue with late 0.5.\* versions that should be fixed now, and the symptoms sound similar to what @RodEsp is describing. I'm not sure you two are having the same issue.

Problems with files not being included or files not being found probably stem from the really simple substitution I make to get the root file list. It just replaces the base dir from each file in the list assuming that the root is where the _SpecRunner is.

It didn't feel good when I was writing it, but it caught all common cases so it was left in pending reevaluation when edge cases come up. This might be one of those edge cases but if it involves traversing beyond the Gruntfile to get source I'm not sure it's common enough (or encouraged enough) to worry about.

I'd be willing to accept a PR if this does turn out to be the issue and a better way to deal with it is found.

**Comment by joshuacc** [comment]
@jsoverson Thanks. Your reply prompted me to investigate a bit more deeply, and it turns out that my problems were self-inflicted. A difficult-to-spot typo was the culprit.

Thanks again for your help, and my apologies for taking up your time!

**Comment by jsoverson** [comment]
@RodEsp, let me know if you have any more information. I'm closing this for now since it seems to be at least partially resolved with @joshuacc's comment.

@joshuacc, what was the typo? It might be worth documenting or putting in some error messaging if it was something the runner could catch.

**Comment by RodEsp** [comment]
Alright, that's cool, thanks.

**Comment by joshuacc** [comment]
@jsoverson It was a typo in the paths to my spec files. The spec files referenced didn't actually exist, so the result was `0 specs, 0 failures in 0.001s.`

I'm not sure if my issue and @RodEsp's issue were the same, though.
