### ISSUE TITLE
_SpecRunner.html copied to working directory and not removed

### ISSUE THREAD

**Issue by vitch** [jasmine-contrib/grunt-jasmine-runner#16]
Firstly, thanks for this very useful plugin - much cleaner than my previous method of tying Jasmine into my build / CI process :)

A little thing I've noticed is that _SpecRunner.html is copied to the working directory when I run this task and isn't deleted when the task finishes. It would be great if the file was deleted when the task completes...

**Comment by jsoverson** [comment]
There was a reason for this at one point, but I can't remember what that would be now. I'll get rid of it, thanks for bringing it up.

**Comment by vitch** [comment]
No problem! Thanks again for the plugin, really cleaned up a bit of our workflow :)

**Comment by jsoverson** [comment]
This has been fixed in the project that will be the future of this task, [grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine) (grunt 0.4.0+)

Thanks!

**Comment by vitch** [comment]
Awesome - thanks for the update :) Looking forward to using the new project when grunt 0.4 comes out :)
