### ISSUE TITLE
how can i allow Access-Control-Allow-Origin with jasmine-server

### ISSUE THREAD

**Issue by ragingwind** [jasmine-contrib/grunt-jasmine-runner#18]
hi i'm jimmy.

i have a question. i'm using grunt-jasmine-runner to make a chrome extension. sometime i have to get data from a different domain via ajax. but server, is launched by grunt with jasmine-server argument, i can't get a any result. as you know, the server is not allowed that according to Access-Control-Allow-Origin. 

how can i configure the server to allow to access a different domain via ajax. like as apache.

**Comment by jsoverson** [comment]
Hi @ragingwind 

This runner has been ported and moved to [grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine) and the server task has been removed and is supported by using other grunt-contrib tasks to start the ad hoc server.

The other server task you will be using going forward (e.g. grunt-contrib-connect) can either already handle this or will need an issue opened regarding it.

Thanks!
