### ISSUE TITLE
Be quiet by default

### ISSUE THREAD

**Issue by cburgmer** [jasmine-contrib/grunt-jasmine-runner#2]
Grunt tasks by default don't make much noise. I'd like the jasmine runner to be equally quiet on the console. Extended output can easily requested by using the -v switch.

**Comment by jsoverson** [comment]
Addressed this and #3. Console reporting is now much less verbose unless an error is encountered. Published to npm.

**Comment by cburgmer** [comment]
Thanks, that was quick. Already running the newest version.
