### ISSUE TITLE
client side testing in jasmine

### ISSUE THREAD

**Issue by bartosz-k** [jasmine-contrib/grunt-jasmine-runner#21]
Hello,

Sorry for bothering and stupid question, but could anyone show me example browser application that can be tested in headless mode with grunt-jasmine-runner? And gruntjs config as well?

Thanks!
Bartek

**Comment by jsoverson** [comment]
This library is being superceded by grunt-contrib-jasmine, and you can view an example setup here : https://github.com/jsoverson/grunt-contrib-jasmine-example
