### ISSUE TITLE
Is it possible to drive phantom and test?

### ISSUE THREAD

**Issue by robdodson** [jasmine-contrib/grunt-jasmine-runner#23]
Sorry if this is a stupid question but I didn't see it mentioned in the readme. I just wanted to know if it's possible to pass a script to phantom, for instance if I wanted to use the `evaluate` method:

``` js
var page = require('webpage').create();
page.open(url, function (status) {
    var title = page.evaluate(function () {
        return document.title;
    });
    console.log('Page title is ' + title);
});
```

If it is possible does it place nice with AMD testing?

**Comment by jsoverson** [comment]
There is no way to do that baked in. I've been focusing on this task's replacement ([grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine)) for the past couple months, awaiting the release of grunt 0.4.0.

This task won't have new features added to it but this seems useful so please bring it up on the [issue tracker](https://github.com/gruntjs/grunt-contrib-jasmine/issues?state=open) for contrib-jasmine.

**Comment by robdodson** [comment]
Cool thanks! I created a new issue so here's the reference if anyone else stumbles on this thread.

https://github.com/gruntjs/grunt-contrib-jasmine/issues/20
