### ISSUE TITLE
Include documentation for all options

### ISSUE THREAD

**Issue by thlorenz** [jasmine-contrib/grunt-jasmine-runner#27]
For example I shouldn't have to read through the code to find out that the `template` cannot just be a path to my template file. Instead it also can be  an `Object` of the form: `{ src: ' ... ', opts: { [ template context ] } }`.

**Comment by jsoverson** [comment]
Thanks for the note, this plugin will be deprecated in favor of [grunt-contrib-jasmine](https://github.com/gruntjs/grunt-contrib-jasmine) in the near future when grunt 0.4.0 is released (hopefully any day now) which has undergone the majority of normalization and quirk fixes.

**Comment by thlorenz** [comment]
Got it.
