### ISSUE TITLE
(Question) Tests pass in browser, but not via command line

### ISSUE THREAD

**Issue by collinforrester** [jasmine-contrib/grunt-jasmine-runner#30]
If I visit my test page through the browser, all the specs pass.

Running 'grunt jasmine' via command line, no tests get executed and I get the error 'Can't find variable require' so I'm wondering if the helpers array is being loaded in the correct order.

My project structure is like this:
/
/src/
/tests/
/tests/SpecRunner.js
/tests/specs/
/grunt.js

I have my main project config for requirejs in grunt.js, but I also have a requirejs config in SpecRunner.js to load the test.

Is my helper supposed to point to the require config for the project or the tests?

Here's the relevant part from grunt.js:

``` javascript
jasmine: {
  amd: true,
  specs: 'tests/spec/**/*spec.js',
  timeout : 10000,
  helpers: [
    "../node_modules/requirejs/require.js",
    "tests/SpecRunner.js"   
 ],  
 junit: {
    output: 'target/junit/'
  }
}
```

In my package.json dependencies I've linked directly to this repo to try the most recent version.

**Comment by jsoverson** [comment]
The helpers are loaded after require.js is, you may need to use a custom template for this option.

Also consider tracking grunt-contrib-jasmine, which will replace this task as soon as grunt 0.4.0 is released. If you are starting a new project, it may be better to start with grunt 0.4.0rc7 in preparation for the release.

**Comment by collinforrester** [comment]
So in my case, "../node_modules/requirejs/require.js" is loaded before "tests/SpecRunner.js"? Also what custom template are you referring to, if you have a link that would be good enough and I could go from there

It's not a new project, but I'll add grunt-contrib-jasmine to the list of things to migrate to when we upgrade grunt versions.

**Comment by jsoverson** [comment]
You can write your own template that you can use to generate the spec runner, the default is [jasmine/SpecRunner.tmpl](https://github.com/jasmine-contrib/grunt-jasmine-runner/blob/670d01ec9f599badaa6ad1fe455a79bef4783889/jasmine/SpecRunner.tmpl) and an example custom template used in the tests is at [test/fixtures/customTemplate/custom.tmpl](https://github.com/jasmine-contrib/grunt-jasmine-runner/blob/master/test/fixtures/customTemplate/custom.tmpl)

How many tasks do you have in your grunt setup now? Many tasks are 0.4.0 compatible and I don't want you to spend too much time troubleshooting this task. Feel free to hit me up for migration questions.

**Comment by collinforrester** [comment]
So that got me alot closer.  It seems that I can't have my test version of the require config and then jasmine test execution code (jasmineEnv.execute()) in the same file though.  If I log out the source variable from jasmine.js inside of grunt-jasmine-runner:

``` html
<!doctype html>
<html>
<head>
    <title>Jasmine Spec Runner</title>
    <link rel="stylesheet" type="text/css" href="/node_modules/grunt-jasmine-runner/jasmine/lib/jasmine-core/jasmine.css">
    <script type="text/javascript" src="/node_modules/grunt-jasmine-runner/jasmine/lib/jasmine-core/jasmine.js"></script>
    <script type="text/javascript" src="/node_modules/grunt-jasmine-runner/jasmine/lib/jasmine-core/jasmine-html.js"></script>
    <script type="text/javascript" src="/node_modules/requirejs/require.js"></script>
    <script type="text/javascript" src="/tests/SpecRunner.js"></script>
    <script type="text/javascript" src="/node_modules/grunt-jasmine-runner/tasks/jasmine/phantom-helper.js"></script>
    <script type="text/javascript" src="/node_modules/grunt-jasmine-runner/tasks/jasmine/reporters/ConsoleReporter.js"></script>
    <script type="text/javascript" src="/node_modules/grunt-jasmine-runner/tasks/jasmine/reporters/JUnitReporter.js"></script>
    <script type="text/javascript" src="/node_modules/grunt-jasmine-runner/tasks/jasmine/jasmine-helper.js"></script>
        <script type="text/javascript">
        require([
            '/tests/spec/core-spec.js' ,
            '/tests/spec/date-spec.js' ,
            '/tests/spec/slidemenu-spec.js' ,
            '/tests/spec/text-input-clear-spec.js' ,
            '/tests/spec/user-feedback-spec.js' ,
            '/tests/spec/userid-spec.js' ,
            '/tests/spec/validation-spec.js'
        ]);
        </script>
</head>
<body>
</body>
</html>
```

Seems like the only thing I need now is the call to jasmine to execute the specs.  previously I had been doing that in my SpecRunner.js file right after my require.config() call.

``` javascript
require([
    'underscore',
    'jquery',
    'jasmine',
    'jasmineJquery',
    'jasmine-html'
  ], function(_, $, jasmine ) {

    var jasmineEnv = jasmine.getEnv();
    jasmineEnv.updateInterval = 1000;

    var htmlReporter = new jasmine.HtmlReporter();

    jasmineEnv.addReporter(htmlReporter);

    var specs = [];
    specs.push( 'spec/core-spec.js' );
    specs.push( 'spec/user-feedback-spec.js' );
    specs.push( 'spec/slidemenu-spec.js' );
    specs.push( 'spec/text-input-clear-spec.js' );
    specs.push( 'spec/validation-spec.js' );
    specs.push( 'spec/userid-spec.js' );
    specs.push( 'spec/date-spec.js' );

    jasmineEnv.specFilter = function(spec) {
      return htmlReporter.specFilter(spec);
    };

    $(function(){
      require( specs, function() {
        jasmineEnv.execute();
      });
    });
});
```

I have quite a few tasks at this point (js, css, min js, min css, release, etc ), but pretty much all of them are using contrib tasks so I'm not too worried about upgrading them since I'm hoping the syntax for the configs don't change too much.  I'm hoping that's mostly true?

**Comment by collinforrester** [comment]
After further thought, I'm just going to take this opportunity to upgrade to the most recent grunt rc.  Thanks for the help today.

**Comment by jsoverson** [comment]
No problem, if you have any issues then feel free to pop in #grunt on freenode or contact me directly.
